---
- hosts: servidores
  tasks:

    - name: Criando multiplos diretorios com permissoes diferentes
      file:
        path: "{{ item.dest }}"
        mode: "{{ item.mode }}"
        state: directory
      with_items:
        - { dest: '/tmp/devops_system1', mode: '0777'}
        - { dest: '/tmp/devops_system2', mode: '0707'}
        - { dest: '/tmp/devops_system3', mode: '0575'}
