- hosts: servidores
- name: Adding Oracle Kernel Parameters
  remote_user: ansible
  become: yes
  become_method: sudo
  lineinfile:
    owner: root
    group: root
    dest: /etc/sysctl.d/99-sysctl.conf
    line: '{{ item }}'
  with_items: 
    - '#### Oracle Install related kernel parameters ###'
    - 'vm.swappiness = 1'
    - 'vm.dirty_background_ratio = 3'
    - 'vm.dirty_ratio = 80'
